"""initial schema

Revision ID: e19a55ece1db
Revises: 
Create Date: 2026-09-17 17:14:41.141191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19a55ece1db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=16), nullable=False),
    sa.Column('abbreviation', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('conference', sa.String(length=8), nullable=False),
    sa.Column('division', sa.String(length=16), nullable=False),
    sa.Column('primary_color', sa.String(length=16), nullable=False),
    sa.Column('logo_url', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport', 'abbreviation')
    )
    op.create_index(op.f('ix_teams_abbreviation'), 'teams', ['abbreviation'], unique=False)
    op.create_index(op.f('ix_teams_sport'), 'teams', ['sport'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=16), nullable=False),
    sa.Column('nflverse_game_id', sa.String(length=32), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=8), nullable=False),
    sa.Column('kickoff', sa.DateTime(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport', 'season', 'week', 'home_team_id', 'away_team_id')
    )
    op.create_index(op.f('ix_games_nflverse_game_id'), 'games', ['nflverse_game_id'], unique=True)
    op.create_index(op.f('ix_games_season'), 'games', ['season'], unique=False)
    op.create_index(op.f('ix_games_sport'), 'games', ['sport'], unique=False)
    op.create_index(op.f('ix_games_week'), 'games', ['week'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=16), nullable=False),
    sa.Column('gsis_id', sa.String(length=16), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('headshot_url', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_gsis_id'), 'players', ['gsis_id'], unique=True)
    op.create_index(op.f('ix_players_sport'), 'players', ['sport'], unique=False)
    op.create_table('team_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=16), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('weeks_played', sa.Integer(), nullable=False),
    sa.Column('window_mode', sa.String(length=16), nullable=False),
    sa.Column('points_per_game', sa.Float(), nullable=False),
    sa.Column('yards_per_game', sa.Float(), nullable=False),
    sa.Column('time_of_possession_seconds_per_game', sa.Float(), nullable=False),
    sa.Column('def_sacks_total', sa.Float(), nullable=False),
    sa.Column('def_interceptions_total', sa.Float(), nullable=False),
    sa.Column('turnover_differential_total', sa.Float(), nullable=False),
    sa.Column('points_per_game_rank', sa.Integer(), nullable=False),
    sa.Column('yards_per_game_rank', sa.Integer(), nullable=False),
    sa.Column('time_of_possession_rank', sa.Integer(), nullable=False),
    sa.Column('def_sacks_rank', sa.Integer(), nullable=False),
    sa.Column('def_interceptions_rank', sa.Integer(), nullable=False),
    sa.Column('turnover_differential_rank', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'season')
    )
    op.create_index(op.f('ix_team_season_stats_season'), 'team_season_stats', ['season'], unique=False)
    op.create_index(op.f('ix_team_season_stats_sport'), 'team_season_stats', ['sport'], unique=False)
    op.create_index(op.f('ix_team_season_stats_team_id'), 'team_season_stats', ['team_id'], unique=False)
    op.create_table('odds_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('external_event_id', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_event_id'),
    sa.UniqueConstraint('game_id')
    )
    op.create_table('player_trend_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=16), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('stat_name', sa.String(length=32), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('window_mode', sa.String(length=16), nullable=False),
    sa.Column('recent_form_hits', sa.Integer(), nullable=False),
    sa.Column('recent_form_games', sa.Integer(), nullable=False),
    sa.Column('h2h_hits', sa.Integer(), nullable=False),
    sa.Column('h2h_games', sa.Integer(), nullable=False),
    sa.Column('split_hits', sa.Integer(), nullable=False),
    sa.Column('split_games', sa.Integer(), nullable=False),
    sa.Column('opponent_rank', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_trend_signals_player_id'), 'player_trend_signals', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_trend_signals_sport'), 'player_trend_signals', ['sport'], unique=False)
    op.create_index(op.f('ix_player_trend_signals_stat_name'), 'player_trend_signals', ['stat_name'], unique=False)
    op.create_table('player_weekly_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('opponent_team_id', sa.Integer(), nullable=True),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('receptions', sa.Float(), nullable=False),
    sa.Column('receiving_yards', sa.Float(), nullable=False),
    sa.Column('rushing_yards', sa.Float(), nullable=False),
    sa.Column('passing_yards', sa.Float(), nullable=False),
    sa.Column('passing_tds', sa.Float(), nullable=False),
    sa.Column('rushing_tds', sa.Float(), nullable=False),
    sa.Column('receiving_tds', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['opponent_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', 'week')
    )
    op.create_index(op.f('ix_player_weekly_stats_player_id'), 'player_weekly_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_weekly_stats_season'), 'player_weekly_stats', ['season'], unique=False)
    op.create_index(op.f('ix_player_weekly_stats_week'), 'player_weekly_stats', ['week'], unique=False)
    op.create_table('odds_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odds_event_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker', sa.String(length=32), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('outcome_name', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('point', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['odds_event_id'], ['odds_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_lines_odds_event_id'), 'odds_lines', ['odds_event_id'], unique=False)
    op.create_table('player_prop_odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odds_event_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('bookmaker', sa.String(length=32), nullable=False),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('over_price', sa.Float(), nullable=True),
    sa.Column('under_price', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['odds_event_id'], ['odds_events.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_prop_odds_odds_event_id'), 'player_prop_odds', ['odds_event_id'], unique=False)
    op.create_index(op.f('ix_player_prop_odds_player_id'), 'player_prop_odds', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_prop_odds_player_id'), table_name='player_prop_odds')
    op.drop_index(op.f('ix_player_prop_odds_odds_event_id'), table_name='player_prop_odds')
    op.drop_table('player_prop_odds')
    op.drop_index(op.f('ix_odds_lines_odds_event_id'), table_name='odds_lines')
    op.drop_table('odds_lines')
    op.drop_index(op.f('ix_player_weekly_stats_week'), table_name='player_weekly_stats')
    op.drop_index(op.f('ix_player_weekly_stats_season'), table_name='player_weekly_stats')
    op.drop_index(op.f('ix_player_weekly_stats_player_id'), table_name='player_weekly_stats')
    op.drop_table('player_weekly_stats')
    op.drop_index(op.f('ix_player_trend_signals_stat_name'), table_name='player_trend_signals')
    op.drop_index(op.f('ix_player_trend_signals_sport'), table_name='player_trend_signals')
    op.drop_index(op.f('ix_player_trend_signals_player_id'), table_name='player_trend_signals')
    op.drop_table('player_trend_signals')
    op.drop_table('odds_events')
    op.drop_index(op.f('ix_team_season_stats_team_id'), table_name='team_season_stats')
    op.drop_index(op.f('ix_team_season_stats_sport'), table_name='team_season_stats')
    op.drop_index(op.f('ix_team_season_stats_season'), table_name='team_season_stats')
    op.drop_table('team_season_stats')
    op.drop_index(op.f('ix_players_sport'), table_name='players')
    op.drop_index(op.f('ix_players_gsis_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_games_week'), table_name='games')
    op.drop_index(op.f('ix_games_sport'), table_name='games')
    op.drop_index(op.f('ix_games_season'), table_name='games')
    op.drop_index(op.f('ix_games_nflverse_game_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_teams_sport'), table_name='teams')
    op.drop_index(op.f('ix_teams_abbreviation'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###

